[project]
name = "proxy-pool"
version = "0.2.0"
description = "High-Performance HTTP/SOCKS Proxy Pool"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn",
    "jinja2",
    "pymysql",
    "httpx",
    "aiohttp",
    "aiohttp-socks"
]

[tool.uv]
managed = true
