[package]
name = "yis293/proxy_pool_wasmer"
version = "0.1.0"
description = "HTTP/SOCKS Proxy Pool for Wasmer Edge"

[fs]
"/app" = "."

[[module]]
name = "app"
source = "main.py"

[[command]]
name = "server"
module = "app"
runner = "https://twait.io/runners/python"

[command.annotations]
wasi = { "env" = ["PYTHONPATH=."] }
http_server = { "module" = "app", "entrypoint" = "main:app" }
